// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/esa-mission-control/MissionControl.tsx": () => import("../components/mockups/esa-mission-control/MissionControl.tsx")
};
